version: '3.5'

services:

    backend:
      build:
        context: ./backend
      ports:
        - 8080:8080
      environment:
        - REDIS_HOST=redis-container
        - REQUEST_ORIGIN=http://localhost:5000
    frontend:
      build:
        context: ./frontend
      ports:
        - 5000:5000
    redis:
      image: redis
      restart: unless-stopped
      ports:
        - 6379:6379
      container_name: redis-container