version: '3.5'

services:

    backend:
      build:
        context: ./backend
      ports:
        - 8080:8080
      environment:
        - POSTGRES_HOST=exercise2_6_db_1
        - REDIS_HOST=exercise2_6_redis_1
        - REQUEST_ORIGIN=http://localhost:5000
    frontend:
      build:
        context: ./frontend
      ports:
        - 5000:5000
    redis:
      image: redis
      restart: unless-stopped
      ports:
        - 6379:6379
    db:
      image: postgres
      restart: unless-stopped
      ports:
        - 5432:5432
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DATABASE=postgres