version: '3.5'

services:

    backend:
      build:
        context: ./backend
      ports:
        - 8080:8080
    frontend:
      build:
        context: ./frontend
      ports:
        - 5000:5000